name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-firefox:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 22
        uses: actions/setup-java@v4.3.0
        with:
          java-version: 22
          distribution: 'temurin'

      - name: Build
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test
        continue-on-error: true

      - name: Generate Allure report
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4.4.0
        with:
          name: allure-report
          path: target/site/allure-maven-plugin